require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
  
Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*_spec.rb'

RSpec/Rails/InferredSpecType:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*.rb'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - 'config/**/*.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
